
class VerbInfo {
  final int verbID;
  final String numero;
  final String es;
  final String presente;
  final String pasado;
  final String participio;
  final String pronunciacion1;
  final String pronunciacion2;
  final String pronunciacion3;
  final String image;
  
  VerbInfo(
    this.verbID, 
    {
      this.numero,
      this.es,
      this.presente,
      this.pasado,
      this.participio,
      this.pronunciacion1,
      this.pronunciacion2,
      this.pronunciacion3,
      this.image,
    }
  );
}

List<VerbInfo> verbos = [
  VerbInfo (1,
  numero: '1',
  es: 'Llorar',
  presente: 'Cry',
  pasado: 'Cried',
  participio: 'Cried',
  pronunciacion1: 'Crai',
  pronunciacion2: 'Craid',
  pronunciacion3: 'Craid',
  image: 'assets/cry.png'),
  VerbInfo(2, 
  numero: '2',
  es: 'Correr',
  presente: 'Run',
  pasado: 'Ran',
  participio: 'Run',
  pronunciacion1: 'Ron',
  pronunciacion2: 'Ran',
  pronunciacion3: 'Ron',
  image: 'assets/run.png'),
  VerbInfo(3, 
  numero: '3',
  es: 'Cargar',
  presente: 'Carry',
  pasado: 'Carried',
  participio: 'Carried',
  pronunciacion1: 'Kerri',
  pronunciacion2: 'Kerrid',
  pronunciacion3: 'Kerrid',
  image: 'assets/carry.png'),
  VerbInfo(4, 
  numero: '4',
  es: 'Observar',
  presente: 'Watch',
  pasado: 'Watched',
  participio: 'Watched',
  pronunciacion1: 'Uatch',
  pronunciacion2: 'Uatcht',
  pronunciacion3: 'Uatcht',
  image: 'assets/watch.png'),
  VerbInfo(5, 
  numero: '5',
  es: 'Volar',
  presente: 'Fly',
  pasado: 'Flew',
  participio: 'Flown',
  pronunciacion1: 'Flai',
  pronunciacion2: 'Fliu',
  pronunciacion3: 'Floun',
  image: 'assets/fly.png'),
  VerbInfo(6, 
  numero: '6',
  es: 'Nadar',
  presente: 'Swim',
  pasado: 'Swam',
  participio: 'Swum',
  pronunciacion1: 'Suim',
  pronunciacion2: 'Suam',
  pronunciacion3: 'Sum',
  image: 'assets/swim.png'),
  VerbInfo(7, 
  numero: '7',
  es: 'Escuchar',
  presente: 'Listen',
  pasado: 'Listened',
  participio: 'Listened',
  pronunciacion1: 'Lisen',
  pronunciacion2: 'Lisent',
  pronunciacion3: 'Lisent',
  image: 'assets/listen.png'),
  VerbInfo(8, 
  numero: '8',
  es: 'Oler',
  presente: 'Smell',
  pasado: 'Smelled',
  participio: 'Smelled',
  pronunciacion1: 'Smel',
  pronunciacion2: 'Smelt',
  pronunciacion3: 'Smelt',
  image: 'assets/smell.png'),
  VerbInfo(9,
  numero: '9', 
  es: 'Lavar',
  presente: 'Wash',
  pasado: 'Washed',
  participio: 'Washed',
  pronunciacion1: 'Uash',
  pronunciacion2: 'Uasht',
  pronunciacion3: 'Uasht',
  image: 'assets/wash.png'),
  VerbInfo(10,
  numero: '10', 
  es: 'Mostrar',
  presente: 'Show',
  pasado: 'Showed',
  participio: 'Showed',
  pronunciacion1: 'Shou',
  pronunciacion2: 'Shouwd',
  pronunciacion3: 'Shouwd',
  image: 'assets/show.png'),
  VerbInfo(11, 
  numero: '11',
  es: 'Jugar',
  presente: 'Play',
  pasado: 'Played',
  participio: 'Played',
  pronunciacion1: 'Plei',
  pronunciacion2: 'Pleied',
  pronunciacion3: 'Pleied',
  image: 'assets/play.png'),
  VerbInfo(12, 
  numero: '12',
  es: 'Guardar',
  presente: 'Save',
  pasado: 'Saved',
  participio: 'Saved',
  pronunciacion1: 'Seib',
  pronunciacion2: 'Seibt',
  pronunciacion3: 'Seibt',
  image: 'assets/save.png'),
  VerbInfo(13, 
  numero: '13',
  es: 'Aprender',
  presente: 'Learn',
  pasado: 'Learned',
  participio: 'Learned',
  pronunciacion1: 'Lern',
  pronunciacion2: 'Lernt',
  pronunciacion3: 'Lernt',
  image: 'assets/learn.png'),
  VerbInfo(14, 
  numero: '14',
  es: 'Ayudar',
  presente: 'Help',
  pasado: 'Helped',
  participio: 'Helped',
  pronunciacion1: 'Jelp',
  pronunciacion2: 'Jelpt',
  pronunciacion3: 'Jelpt',
  image: 'assets/help.png'),
  VerbInfo(15, 
  numero: '15',
  es: 'Platicar',
  presente: 'Talk',
  pasado: 'Talked',
  participio: 'Talked',
  pronunciacion1: 'Tok',
  pronunciacion2: 'Tokt',
  pronunciacion3: 'Tokt',
  image: 'assets/talk.png'),
  VerbInfo(16, 
  numero: '16',
  es: 'Limpiar',
  presente: 'Clean',
  pasado: 'Cleaned',
  participio: 'Cleaned',
  pronunciacion1: 'Clin',
  pronunciacion2: 'Clint',
  pronunciacion3: 'Clint',
  image: 'assets/clean.png'),
  VerbInfo(17, 
  numero: '17',
  es: 'Vender',
  presente: 'Sell',
  pasado: 'Sold',
  participio: 'Sold',
  pronunciacion1: 'Sel',
  pronunciacion2: 'Sold',
  pronunciacion3: 'Sold',
  image: 'assets/sell.png'),
  VerbInfo(18, 
  numero: '18',
  es: 'Pintar',
  presente: 'Paint',
  pasado: 'Painted',
  participio: 'Painted',
  pronunciacion1: 'Peint',
  pronunciacion2: 'Peined',
  pronunciacion3: 'Peined',
  image: 'assets/paint.png'),
  VerbInfo(19, 
  numero: '19',
  es: 'Saltar',
  presente: 'Jump',
  pasado: 'Jumped',
  participio: 'Jumped',
  pronunciacion1: 'Yomp',
  pronunciacion2: 'Yompt',
  pronunciacion3: 'Yompt',
  image: 'assets/jump.png'),
  VerbInfo(20, 
  numero: '20',
  es: 'Dormir',
  presente: 'Sleep',
  pasado: 'Slept',
  participio: 'Slept',
  pronunciacion1: 'Slip',
  pronunciacion2: 'Slept',
  pronunciacion3: 'Slept',
  image: 'assets/sleep.png'),
  VerbInfo(21, 
  numero: '21',
  es: 'Conducir',
  presente: 'Drive',
  pasado: 'Drove',
  participio: 'Driven',
  pronunciacion1: 'Draib',
  pronunciacion2: 'Droub',
  pronunciacion3: 'Draiben',
  image: 'assets/drive.png'),
  VerbInfo(22, 
  numero: '22',
  es: 'Cantar',
  presente: 'Sing',
  pasado: 'Sang',
  participio: 'Sung',
  pronunciacion1: 'Sinj',
  pronunciacion2: 'Sanj',
  pronunciacion3: 'Sunj',
  image: 'assets/sing.png'),
  VerbInfo(23, 
  numero: '23',
  es: 'Bailar',
  presente: 'Dance',
  pasado: 'Danced',
  participio: 'Danced',
  pronunciacion1: 'Dens',
  pronunciacion2: 'Denst',
  pronunciacion3: 'Denst',
  image: 'assets/dance.png'),
  VerbInfo(24, 
  numero: '24',
  es: 'Descansar',
  presente: 'Rest',
  pasado: 'Rested',
  participio: 'Rested',
  pronunciacion1: 'Rest',
  pronunciacion2: 'Rested',
  pronunciacion3: 'Rested',
  image: 'assets/rest.png'),
  VerbInfo(25, 
  numero: '25',
  es: 'Llover',
  presente: 'Rain',
  pasado: 'Rained',
  participio: 'Rained',
  pronunciacion1: 'Rein',
  pronunciacion2: 'Reint',
  pronunciacion3: 'Reint',
  image: 'assets/rain.png'),
  VerbInfo(26, 
  numero: '26',
  es: 'Despertar',
  presente: 'Wake Up',
  pasado: 'Woke Up',
  participio: 'Woken Up',
  pronunciacion1: 'Ueik Op',
  pronunciacion2: 'Uouk Op',
  pronunciacion3: 'Uouken Op',
  image: 'assets/wake.png'),
];

List<VerbInfo> verbosGe = [
  VerbInfo (1,
  numero: '1',
  es: 'Weinen',
  presente: 'Cry',
  pasado: 'Cried',
  participio: 'Cried',
  pronunciacion1: 'Crai',
  pronunciacion2: 'Craid',
  pronunciacion3: 'Craid',
  image: 'assets/cry.png'),
  VerbInfo(2, 
  numero: '2',
  es: 'Correr',
  presente: 'Run',
  pasado: 'Ran',
  participio: 'Run',
  pronunciacion1: 'Ron',
  pronunciacion2: 'Ran',
  pronunciacion3: 'Ron',
  image: 'assets/run.png'),
];